version: '2'
services:
  ddns_service:
    build: .
    command: hug -f server.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - ddns

networks:
  ddns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.16.0/24
          gateway: 172.30.16.1
