version: '2'
services:
  ddns_service:
    build: .
    command: ["gunicorn", "server:__hug_wsgi__", "-k", "gevent", "--bind", "0.0.0.0:8888"]
    volumes:
      - .:/code
    ports:
      - "8800:8000"
    networks:
      - ddns
  http_server:
    image: nginx
    volumes:
      - ./nginx_cfg/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    networks:
      - ddns
    depends_on:
      - ddns_service

networks:
  ddns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.16.0/24
          gateway: 172.30.16.1
